enum SupatermUITestIdentifier {
  enum Accessibility {
    static let sidebarSpaceButton = "sidebar.space-button"
    static let sidebarCreateSpaceButton = "sidebar.create-space-button"
    static let sidebarTabRow = "sidebar.tab-row"
    static let sidebarPinnedSection = "sidebar.pinned-section"
    static let sidebarRegularSection = "sidebar.regular-section"
    static let paletteInput = "palette.input"
    static let paletteResultRow = "palette.result-row"
    static let dialogConfirm = "dialog.confirm"
    static let dialogCancel = "dialog.cancel"
    static let dialogSpaceName = "dialog.space-name"
    static let dialogQuit = "dialog.quit"
    static let dialogQuitTerminate = "dialog.quit.terminate"
    static let dialogQuitPreserve = "dialog.quit.preserve"
  }

  enum MenuItemIdentifier: String {
    case about = "app.supabit.supaterm.app.about"
    case checkForUpdates = "app.supabit.supaterm.app.checkForUpdates"
    case quit = "app.supabit.supaterm.app.quit"
    case quitTerminatingSessions = "app.supabit.supaterm.app.quitTerminatingSessions"
    case settings = "app.supabit.supaterm.app.settings"
    case newWindow = "app.supabit.supaterm.file.newWindow"
    case newTab = "app.supabit.supaterm.file.newTab"
    case splitRight = "app.supabit.supaterm.file.splitRight"
    case splitLeft = "app.supabit.supaterm.file.splitLeft"
    case splitDown = "app.supabit.supaterm.file.splitDown"
    case splitUp = "app.supabit.supaterm.file.splitUp"
    case closeSurface = "app.supabit.supaterm.file.close"
    case closeTab = "app.supabit.supaterm.file.closeTab"
    case closeWindow = "app.supabit.supaterm.file.closeWindow"
    case closeAllWindows = "app.supabit.supaterm.file.closeAllWindows"
    case terminateAllTerminalSessions = "app.supabit.supaterm.file.terminateAllTerminalSessions"
    case openCommandPalette = "app.supabit.supaterm.file.openCommandPalette"
    case copy = "app.supabit.supaterm.edit.copy"
    case paste = "app.supabit.supaterm.edit.paste"
    case pasteSelection = "app.supabit.supaterm.edit.pasteSelection"
    case selectAll = "app.supabit.supaterm.edit.selectAll"
    case find = "app.supabit.supaterm.edit.find"
    case findNext = "app.supabit.supaterm.edit.findNext"
    case findPrevious = "app.supabit.supaterm.edit.findPrevious"
    case hideFindBar = "app.supabit.supaterm.edit.hideFindBar"
    case selectionForFind = "app.supabit.supaterm.edit.selectionForFind"
    case toggleSidebar = "app.supabit.supaterm.view.toggleSidebar"
    case toggleAgentPanel = "app.supabit.supaterm.view.toggleAgentPanel"
    case forkAgentSession = "app.supabit.supaterm.view.forkAgentSession"
    case copyAgentSessionID = "app.supabit.supaterm.view.copyAgentSessionID"
    case changeTabTitle = "app.supabit.supaterm.view.changeTabTitle"
    case changeTerminalTitle = "app.supabit.supaterm.view.changeTerminalTitle"
    case nextTab = "app.supabit.supaterm.tabs.next"
    case previousTab = "app.supabit.supaterm.tabs.previous"
    case selectLastTab = "app.supabit.supaterm.tabs.last"
    case zoomSplit = "app.supabit.supaterm.window.zoomSplit"
    case previousSplit = "app.supabit.supaterm.window.previousSplit"
    case nextSplit = "app.supabit.supaterm.window.nextSplit"
    case selectSplitAbove = "app.supabit.supaterm.window.selectSplitAbove"
    case selectSplitBelow = "app.supabit.supaterm.window.selectSplitBelow"
    case selectSplitLeft = "app.supabit.supaterm.window.selectSplitLeft"
    case selectSplitRight = "app.supabit.supaterm.window.selectSplitRight"
    case equalizeSplits = "app.supabit.supaterm.window.equalizeSplits"
    case moveSplitDividerUp = "app.supabit.supaterm.window.moveSplitDividerUp"
    case moveSplitDividerDown = "app.supabit.supaterm.window.moveSplitDividerDown"
    case moveSplitDividerLeft = "app.supabit.supaterm.window.moveSplitDividerLeft"
    case moveSplitDividerRight = "app.supabit.supaterm.window.moveSplitDividerRight"
    case submitGitHubIssue = "app.supabit.supaterm.help.submitGitHubIssue"
    case changelog = "app.supabit.supaterm.help.changelog"

    var menuTitle: String {
      switch rawValue.split(separator: ".")[3] {
      case "app": "Supaterm"
      case "file": "File"
      case "edit": "Edit"
      case "view": "View"
      case "tabs": "Tabs"
      case "spaces": "Spaces"
      case "window": "Window"
      case "help": "Help"
      default: preconditionFailure("Unknown menu item identifier: \(rawValue)")
      }
    }
  }
}
