name: Setup macOS build deps
description: Install macOS build deps and build GhosttyKit

runs:
  using: composite
  steps:
    - run: brew install mise
      shell: bash
    - run: mise install
      shell: bash
    - run: make build-ghostty-xcframework
      shell: bash
