name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-26
    permissions:
      contents: read
      id-token: write
    env:
      MISE_HTTP_TIMEOUT: 120
      MISE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-macos
      - run: make mac-lint
      - run: make mac-tuist-install
      - run: make mac-tuist-generate
      - run: make mac-build-ghostty
      - run: make mac-test-xcodebuild
