name: warm-cache

on:
  push:
    branches:
      - main
    paths:
      - ".github/actions/setup-macos/**"
      - ".github/actions/setup-mise/**"
      - ".github/workflows/warm-cache.yml"
      - "apps/Configurations/**"
      - "apps/mac/**"
      - "apps/shared/**"
      - "apps/Tuist.mk"
      - "apps/Tuist.swift"
      - "apps/Tuist/**"
      - "apps/Workspace.swift"
      - "Makefile"
      - "mise.toml"

concurrency:
  group: warm-cache
  cancel-in-progress: true

permissions:
  contents: read

env:
  MISE_HTTP_TIMEOUT: 120

jobs:
  warm_cache:
    name: warm-cache
    runs-on: macos-26
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-macos
        with:
          cache-native-builds: false
          github-token: ${{ github.token }}
        env:
          TUIST_TOKEN: ${{ secrets.TUIST_TOKEN }}
      - run: make mac-warm-cache TUIST_BINARY_CACHE_PROFILE=all-possible
        env:
          TUIST_TOKEN: ${{ secrets.TUIST_TOKEN }}
      - run: make mac-warm-cache TUIST_CONFIGURATION=Release
        env:
          TUIST_TOKEN: ${{ secrets.TUIST_TOKEN }}
